# Generated by Django 5.2 on 2025-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('handicap', 'Handicap'), ('motorcycle', 'Motorcycle'), ('reserved', 'Reserved')], max_length=20),
        ),
    ]
