# Generated by Django 5.2 on 2025-07-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingspot_spot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('motorcycle', 'Motorcycle'), ('reserved', 'Reserved')], max_length=20),
        ),
    ]
