# Generated by Django 5.2 on 2025-07-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_payment_alter_booking_cost_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
