# Generated by Django 5.2 on 2025-04-20 22:08

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='motorist',
            managers=[
                ('objects', users.models.PersonManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', users.models.PersonManager()),
            ],
        ),
    ]
