# Generated by Django 5.2 on 2025-04-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_motorist_managers_alter_person_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorist',
            options={},
        ),
        migrations.AlterModelTable(
            name='motorist',
            table='motorists',
        ),
    ]
