# Generated by Django 5.2 on 2025-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_person_username_alter_otp_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_value',
            new_name='otp',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='person',
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
